name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'The type of release. Must be major, minor or patch'
        required: true
jobs:
  create_release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release Branch
        env:
          GITHUB_CHANGELOG_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install github_changelog_generator
          Scripts/release.sh --${{ github.event.inputs.release-type }}
          git push origin HEAD
